### ISSUE TITLE
Think about how we might specify paramaterised jobs

### ISSUE THREAD

**Issue by evansd** [opensafely/job-runner#28]
This is prompted by the work we've been doing on the `project.yaml` [here](https://github.com/opensafely/school-age-children-and-covid/compare/add-project-file). This file ends up very repetitive because it often ends up running the same scripts with slightly different arguments. So much so that it would be very awkward to write by hand.

It would be nice to be able to support these kinds of projects without having to generate the `project.yaml` using a script. I'm thinking of something like the build matrix support you get in CI systems, but I don't yet have a clear vision for how it could all work. It's certainly going to involve variable interpolation (you'll be pleased to hear!).

**Comment by sebbacon** [comment]
So there's a couple of use cases here.

1. A kind of build matrix where the parameters are hard-coded in the yaml.  We might as well borrow the [Github syntax](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategy) (noting it will produce a maximum of 256 actions):

```yaml
strategy:
  matrix:
    node: [6, 8, 10]
steps:
  # Configures the node version used on GitHub-hosted runners
  - uses: actions/setup-node@v1
    with:
      # The Node.js version to configure
      node-version: ${{ matrix.node }}
```

2. It may be that you want to use parameters which are the output of other actions. This would require something like [this](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6):

```yaml
name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: build
```
